import React from 'react';
import { BarChart3, BrainCircuit, ShieldCheck, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import BrandLogo from '../components/BrandLogo';
import Footer from '../components/Footer';
import { useTheme } from '../context/ThemeContext';

const principles = [{ icon: BrainCircuit, title: 'Clarity over noise', text: 'The best trading tools make your decisions easier to review—not harder to find.' }, { icon: BarChart3, title: 'Progress over perfection', text: 'A useful journal turns imperfect data into a more disciplined process, one review at a time.' }, { icon: ShieldCheck, title: 'Trust by design', text: 'Your performance data deserves a secure home and a product that respects your attention.' }];
const About = () => { const { theme, toggleTheme } = useTheme(); return <div className="gt-marketing"><header className="gt-public-nav"><Link to="/"><BrandLogo /></Link><nav><Link to="/about">Why Genius Trader</Link><Link to="/pricing">Pricing</Link></nav><div className="gt-public-nav__actions"><button className="gt-icon-button" onClick={toggleTheme} aria-label="Change colour theme">{theme === 'dark' ? '☀' : '◐'}</button><Link className="gt-login-link" to="/login">Sign in</Link><Link className="gt-primary-button" to="/signup">Start for free</Link></div></header><main className="gt-about"><section className="gt-about__hero"><div className="gt-eyebrow">ABOUT GENIUS TRADER</div><h1>Better traders are built in the review.</h1><p>Genius Trader was created for people who know that consistent improvement comes from a calm process, not a louder screen.</p></section><section className="gt-about__story"><div><span>OUR BELIEF</span><h2>Your journal should feel like a trusted coach.</h2></div><p>Every trade holds a lesson. We bring together the context, outcomes, and risk decisions that make those lessons visible—so you can recognise what works, remove what doesn’t, and keep moving forward with intention.</p></section><section className="gt-principles">{principles.map(({ icon: Icon, title, text }, index) => <article key={title}><span>0{index + 1}</span><Icon size={25} /><h3>{title}</h3><p>{text}</p></article>)}</section><section className="gt-about__close"><h2>Thoughtful tools. Better decisions.</h2><p>Start recording the process behind your performance today.</p><Link className="gt-primary-button gt-hero-cta" to="/signup">Create your free account <ArrowRight size={18} /></Link></section></main><Footer /></div>; };
export default About;
