import React from 'react';
import { Check, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import BrandLogo from '../components/BrandLogo';
import Footer from '../components/Footer';
import { useTheme } from '../context/ThemeContext';

const plans = [{ name: 'Starter', price: '₹0', note: 'For building the habit', features: ['Trade journal', 'Core performance metrics', 'Risk tools', 'Cloud sync'] }, { name: 'Genius Pro', price: '₹499', note: 'For the committed trader', features: ['Everything in Starter', 'Advanced analytics', 'Excel import & exports', 'Priority support'], featured: true }, { name: 'Desk', price: 'Let’s talk', note: 'For teams and educators', features: ['Everything in Genius Pro', 'Shared workflows', 'Custom reporting', 'Dedicated onboarding'] }];
const Pricing = () => { const { theme, toggleTheme } = useTheme(); return <div className="gt-marketing"><header className="gt-public-nav"><Link to="/"><BrandLogo /></Link><nav><Link to="/about">Why Genius Trader</Link><Link to="/pricing">Pricing</Link></nav><div className="gt-public-nav__actions"><button className="gt-icon-button" onClick={toggleTheme} aria-label="Change colour theme">{theme === 'dark' ? '☀' : '◐'}</button><Link className="gt-login-link" to="/login">Sign in</Link><Link className="gt-primary-button" to="/signup">Start for free</Link></div></header><main className="gt-pricing"><div className="gt-pricing__intro"><div className="gt-eyebrow">SIMPLE, HONEST PRICING</div><h1>Invest in your process.</h1><p>Start with everything you need to journal better. Upgrade only when your process is ready for more.</p></div><section className="gt-price-grid">{plans.map(plan => <article className={`gt-price-card ${plan.featured ? 'gt-price-card--featured' : ''}`} key={plan.name}>{plan.featured && <span className="gt-price-badge">MOST POPULAR</span>}<h2>{plan.name}</h2><p>{plan.note}</p><div className="gt-price"><strong>{plan.price}</strong>{plan.price !== '₹0' && plan.price !== 'Let’s talk' && <span>/ month</span>}</div><Link to="/signup" className={plan.featured ? 'gt-primary-button' : 'gt-secondary-button'}>{plan.name === 'Desk' ? 'Talk to us' : 'Start free'} <ArrowRight size={16} /></Link><ul>{plan.features.map(feature => <li key={feature}><Check size={16} />{feature}</li>)}</ul></article>)}</section><div className="gt-pricing__assurance">No hidden fees. No payment details required to start. Cancel any time.</div></main><Footer /></div>; };
export default Pricing;
